name: "Build MacOS App"

on:
  push:
    branches: ["main"]
    tags: ["*"]
  workflow_dispatch:

jobs:
  build-app:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Lix GHA Installer Action
        uses: samueldr/lix-gha-installer-action@v2026-02-22
        with:
          extra_nix_config: experimental-features = nix-command flakes flake-self-attrs

      - name: Build app
        run: nix develop --command bash -c "flutter pub get && dart scripts/generate.dart && flutter pub run build_runner build && flutter build macos --release"

      - name: Upload installer artifact
        uses: actions/upload-artifact@v6
        with:
          name: App
          path: build/macos/Build/Products/Release/Nexus.app